### ISSUE TITLE
Bugs e sugestões

### ISSUE THREAD

**Issue by VitorBSP** [AlissonRP/mypdf1#12]
`devtools::install_github("https://github.com/AlissonRP/mypdf1")`
Error: .onLoad falhou em loadNamespace() para 'pkgload', detalhes:
  chamada: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
  erro: namespace ‘rlang’ 0.4.11 is already loaded, but >= 1.0.1 is required

Outro, por causa do round(), o total de probabilidades fica arredondado, talvez arredondar depois do total.

`arrange(desc(absolute_frequency))`
Faz com que o total fique em primeiro, talvez já estar dentro da função uma ordenador  ou criar uma feature para fazer com o que total fique sempre em último.

**Comment by AlissonRP** [comment]
You need to update your [`rlang`](https://cran.r-project.org/web/packages/rlang/index.html) package
```r
install.packages("rlang")
#tip: old.packages()
```
It seems resolved in https://github.com/AlissonRP/mypdf1/commit/5581c763946402622fbf188960f0e25f2ae1ea94
* Probabilities
```r
PlantGrowth |> 
  mypdf1::pdf1_tbl_freq(group)
#> # A tibble: 4 × 3
#>   group absolute_frequency relative_frequency
#>   <chr>              <int>              <dbl>
#> 1 ctrl                  10              0.333
#> 2 trt1                  10              0.333
#> 3 trt2                  10              0.333
#> 4 Total                 30              1.00
```

`pdf1_tbl_freq` in the new version will have two new parameters:
* param `sort_by`:      variable you want to sort the `tibble` (By default the `sort_by` is in alphabetical order (lexical order more precisely) of `{{var}}`)
* param `desc`:  if you want decreasing order put `T` (default is `FALSE`)

## Examples

* sort by `absolute_frequency`
```r
mtcars |> 
  mypdf1::pdf1_tbl_freq(gear, sort_by = absolute_frequency)
#> # A tibble: 4 × 3
#>   gear  absolute_frequency relative_frequency
#>   <chr>              <int>              <dbl>
#> 1 5                      5              0.156
#> 2 4                     12              0.375
#> 3 3                     15              0.469
#> 4 Total                 32              1

```
* sort by `relative_frequency` and decreasing
```r
mtcars |> 
  mypdf1::pdf1_tbl_freq(gear, sort_by = relative_frequency, desc = T)
#> # A tibble: 4 × 3
#>   gear  absolute_frequency relative_frequency
#>   <chr>              <int>              <dbl>
#> 1 3                     15              0.469
#> 2 4                     12              0.375
#> 3 5                      5              0.156
#> 4 Total                 32              1
```

* default
```r
mtcars |> 
  mypdf1::pdf1_tbl_freq(gear)
#> # A tibble: 4 × 3
#>   gear  absolute_frequency relative_frequency
#>   <chr>              <int>              <dbl>
#> 1 3                     15              0.469
#> 2 4                     12              0.375
#> 3 5                      5              0.156
#> 4 Total                 32              1

```

**Comment by VitorBSP** [comment]
Thanks man, the sky is the limit!
