### ISSUE TITLE
New Names

### ISSUE THREAD

**Issue by AlissonRP** [AlissonRP/mypdf1#20]
1. rep2ez
2. torep
3. fastrep
4. forrep

<details>
  <summary markdown="span">tasks</summary>

* I need to change
 - [x] All the examples on the docs
 - [x] all name of functions (oh gooddd)
 - [x] readme
 - [x] vignetes
 - [x] description
 - [x] gh actions
 - [x] repo name
 - [x] templates name
 - [x] edit all tests
 - [x] new logo

<details>
  <summary markdown="span">whyyyy</summary>

Ah, ah, ah, ah
Tumbling down
Tumbling down
Tumbling down
Ah, ah, ah, ah
Letting me down
Letting me down
Letting me down
<p align="center"><img align="center" src="https://giffiles.alphacoders.com/112/112708.gif" height="150px" width="390"/></p>
</details>
</details>

**Comment by VitorBSP** [comment]
I prefer fastrep because is more comprehensible.
Before you choose a new name and a new abbreviation (will have?) I can help with functions names, tests and descriptions

**Comment by AlissonRP** [comment]
I don't pretend to change the name "right" now,  so more options are welcome. 
I will have to change everything (grrrr crannnn) so I have to decide on a **GOOD** name. 

At this moment the unique function which will conflict with names is `summary` (if remove the prefix) so idk tbh.

Looks cool write 

```r
df |>
 tbl()
```

The only truth is that the `pdf` in the name is dead.
